### ISSUE TITLE
Documentation around job request upload parameters is unclear

### ISSUE THREAD

**Issue by brandonparis** [voxel51/api-py#35]
This simple job request does not result in a started job:

```
job_request = JobRequest("vehicle-tracker")
job_request.set_input("file", data_id=data_id)
job_request.set_parameter("job_name", "tracker-test")
job_request.set_parameter("auto_start", True)
```

**Comment by brimoor** [comment]
That's not how the API works. From https://dev.console.voxel51.com/docs/analytics?python#vehicle-tracker:

```py
job_request = JobRequest("vehicle-tracker")
job_request.set_input("video", data_id=data_id)
job_request.set_parameter("fps", 15)  # optional
job = api.upload_job_request(
    job_request, "vehicle-tracker-test", auto_start=True, use_gpu=True)
```

**Comment by brandonparis** [comment]
Cool then this is outdated:

https://dev.console.voxel51.com/docs/api?python#jobs-upload-job-request

**Comment by brimoor** [comment]
`set_parameter` is for parameters of the actual job. I.e., the only supported "parameters" for an analytic are explicitly documented in the analytic JSON.

"auto start" is a meta parameter that is passed directly to the `upload_job_request` method.

We haven't done any error checking client side so your non-existent "auto_start" param is basically silently ignored. We could consider changing that, but not essential for now I don't think.

**Comment by brandonparis** [comment]
<img width="1218" alt="Screen Shot 2019-04-02 at 4 30 13 PM" src="https://user-images.githubusercontent.com/17344791/55434036-9e27a680-5564-11e9-99e7-bdd1e9c4f4bc.png">

If I'm looking at this documentation trying to write a script (which I'm actually doing) it's pretty unclear and seems to suggest that I would set the auto_start parameter as I described above.

I just think this is maybe at worst inconsistent documentation

**Comment by Brandonprs** [comment]
> "auto start" is a meta parameter that is passed directly to the `upload_job_request` method.
Nothing indicates to me that this is a meta_parameter that is passed to that method here. This suggests every parameter I want is explicitly passed with set_parameter

**Comment by brandonparis** [comment]
> "auto start" is a meta parameter that is passed directly to the `upload_job_request` method.

Nothing indicates to me that this is a meta_parameter that is passed to that method here. This suggests every parameter I want is explicitly passed with set_parameter

**Comment by brimoor** [comment]
upon closer inspection, I definitely see how the `Parameters` section on the left can be interpreted to mean that these are things you should put in `set_parameter` on the right (not the case).

I'll revise to make it more clear.

**Comment by brimoor** [comment]
This was addressed in some recent merges from me.
