### ISSUE TITLE
Add support for `VOXEL51_API_PRIVATE_KEY` environment variable

### ISSUE THREAD

**Issue by brimoor** [voxel51/api-py#80]
We could support creating API sessions by simply setting an `VOXEL51_API_KEY` environment variable that contains _only_ one's private key, rather than forcing the user to have the entire token on disk, pointed to by `VOXEL51_API_TOKEN`

**Comment by MikeJeffers** [comment]
This however will decouple one's private key from the base_url of the API instance that might have generated this key.

**Comment by lethosor** [comment]
Pretty sure this was addressed in #81

**Comment by brimoor** [comment]
yep this is done and done. `VOXEL51_API_PRIVATE_KEY` for the private key and optionally `VOXEL51_API_BASE_URL` to customize the base API URL
